# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Hugo Theme Pure XS"
license = "MIT"
licenselink = "https://github.com/ranaparth/hugo-theme-purexs/blob/master/LICENSE"
description = "A powerful and pure theme for hugo~enjoy~"
homepage = "https://ranaparth.github.io/"
tags = [
  "blog",
  "clean",
  "simple",
  "dark",
  "white",
  "search"
]
features = [
  "blog",
  "search",
  "tags",
  "categories",
  "about"
]
min_version = "0.57.2"

# If the theme has multiple authors
authors = [
  {name = "xiaoheiah", homepage = "https://xiaohei.im"},
  {name = "ranaparth", homepage = "https://ranaparth.github.io"}
]

[original]
name = "hexo-theme-pure"
homepage = "https://blog.cofess.com"
repo = "https://github.com/cofess/hexo-theme-pure"
